#ifndef _CB_KBD_KBDIO_H_
#define _CB_KBD_KBDIO_H_

enum KBD_ENCODER_IO {
	KBD_ENC_INPUT_BUF	=	0x60,
	KBD_ENC_CMD_REG	=	0x60
};
 
enum KBD_CTRL_IO {
 
	KKBD_CTRL_STATS_REG	=	0x64,
	KBD_CTRL_CMD_REG	=	0x64
};

#endif